
### Comandos Básicos de NumPy

 Creación de Arrays

- ``np.array([lista])``: Crea un array a partir de una lista o lista de listas.
- ``np.zeros((filas, columnas))``: Crea una matriz de ceros.
- ``np.ones((filas, columnas))``: Crea una matriz de unos.
- ``np.eye(N)``: Crea una matriz identidad de tamaño N.
- ``np.arange(inicio, fin, paso)``: Crea un array con valores desde inicio hasta fin con un paso específico.
- ``np.linspace(inicio, fin, num)``: Crea un array de num elementos equidistantes entre inicio y fin.

 Atributos de Arrays

- ``array.shape``: Devuelve una tupla con las dimensiones del array.
- ``array.size``: Devuelve el número total de elementos en el array.
- ``array.ndim``: Devuelve el número de dimensiones del array.
- ``array.dtype``: Devuelve el tipo de dato de los elementos del array.

 Operaciones Básicas

- ``array + array``: Suma de arrays.
- ``array - array``: Resta de arrays.
- ``array * array``: Multiplicación elemento a elemento.
- ``array / array``: División elemento a elemento.
- ``np.dot(array1, array2)``: Producto matricial.
- ``array @ array``: Producto matricial (operador @).

 Funciones Matemáticas

- ``np.sum(array)``: Suma de todos los elementos del array.
- ``np.mean(array)``: Media de los elementos del array.
- ``np.std(array)``: Desviación estándar de los elementos del array.
- ``np.min(array)``: Valor mínimo del array.
- ``np.max(array)``: Valor máximo del array.
- ``np.sqrt(array)``: Raíz cuadrada de cada elemento del array.
- ``np.exp(array)``: Exponencial de cada elemento del array.
- ``np.log(array)``: Logaritmo natural de cada elemento del array.

 Funciones de Indexación y Segmentación

- ``array[index]``: Acceso a un elemento específico.
- ``array[start:stop:step]``: Segmentación de arrays.
- ``np.diagonal(array)``: Devuelve los elementos de la diagonal de una matriz.
- ``np.transpose(array)``: Transpone la matriz.
- ``array.T``: Transpone la matriz (método corto).

 Funciones de Álgebra Lineal

- ``np.linalg.inv(array)``: Inversa de una matriz.
- ``np.linalg.det(array)``: Determinante de una matriz.
- ``np.linalg.eig(array)``: Autovalores y autovectores de una matriz cuadrada.
- ``np.linalg.solve(A, b)``: Resuelve el sistema de ecuaciones lineales Ax = b.


Detalles:
- Mientras mas cerca este el factor de convergencia de 0 mas rapido converge

Condiciones:
- ser matriz cuadrada
- ningun elemento de la diagonal puede ser 0

Premisas (si cumple es convergente):
- Tener diagonal predominante es la condicion necesaria para poder aplicar los metodos, en caso de no tener se deba hacer cambios entre filas
- El factor de convergencia debe ser menor que 1

Importar Libreria y declarar matrices

In [13]:
import numpy as np 

A = np.array([ [8.0, 3.0, 1.0], [2.0, 7.0, -1.0], [-6.0, 0.0, 8.0]])
B = np.array([13.0, 6.0, 2.0])

M = A.copy()
C = B.copy()
cant_filas = A.shape[0]
Apositiva = np.abs(A)


print("Matriz A:")
print(A)
print("")
print("Matriz B:")
print(B)


Matriz A:
[[ 8.  3.  1.]
 [ 2.  7. -1.]
 [-6.  0.  8.]]

Matriz B:
[13.  6.  2.]


### diagoonal predominante

In [14]:
i = 0
buleano = True

while i < cant_filas and buleano:
    fila = Apositiva[i]
    diagonal = Apositiva[i][i]
    if diagonal <= (np.sum(fila) - diagonal):
        print("La matriz no tiene diagonal Predominante")
        buleano = False
    i += 1
    
if buleano:
    print("La matriz si tiene diagonal Predominante")

La matriz si tiene diagonal Predominante


### Hallar la matriz M

In [15]:
i = 0

print(f"Matriz M:")
while i<cant_filas:
    diagonal = A[i][i]
    A[i][i] = 0
    fila = A[i]
    fila = fila / diagonal * -1
    M[i] = fila
    
    C[i] = B[i] / diagonal
    
    i += 1
 
print(M)   
print(f"")
print(f"")
print(f"Matriz C")
print(f"{C}")

Mpositiva = np.abs(M)


Matriz M:
[[-0.         -0.375      -0.125     ]
 [-0.28571429 -0.          0.14285714]
 [ 0.75       -0.         -0.        ]]


Matriz C
[1.625      0.85714286 0.25      ]


### Calcular factor de convergencia

In [16]:
i = 0
mayor = -1
factorConvergencia = 0.0

while i < cant_filas:
    fila = Apositiva[i]
    diagonal = Apositiva[i][i]
        
    factorConvergencia = (np.sum(fila) - diagonal) / diagonal
    if factorConvergencia > mayor:
        mayor = factorConvergencia
    i += 1

factor_conA_deJacobi = mayor
print("Factor de convergencia:")
print(f"De jacobi con A: {factor_conA_deJacobi}")


i = 0
mayor = -1
factorConvergencia = 0.0

while i < cant_filas:
    fila = Mpositiva[i]
    factorConvergencia = np.sum(fila) 
    
    if factorConvergencia > mayor:
        mayor = factorConvergencia
    i += 1
    
factor_conM_deJacobi = mayor   
print(f"De jacobi con M: {factor_conM_deJacobi}")



i = 0
j = 0

Q = 0.0
P = 0.0
mayor = -1
esPiso = True
factorConvergencia = 0.0

while i < cant_filas:  
    while j < cant_filas:
        if(j == i):
            esPiso = False
        if(esPiso):
            P += Mpositiva[i][j]
        else:
            Q += Mpositiva[i][j]
        j += 1
    
    factorConvergencia = Q/(1-P)
    
    if factorConvergencia > mayor:
        mayor = factorConvergencia
    
    j = 0
    i += 1
    P = 0.0
    Q = 0.0
    esPiso = True
            
         
factor_conM_deSeigel = mayor
print(f"De Seigel con M: {factor_conM_deSeigel}")

Factor de convergencia:
De jacobi con A: 0.75
De jacobi con M: 0.75
De Seigel con M: 0.5


In [20]:
#Requerimientos
iteraciones = 17
tolerancia = 0.0000005
redondeado = True

Xo = np.array([0, 0, 0])
X1 = np.array([0, 0, 0])

cosita = factor_conA_deJacobi / (1 - factor_conA_deJacobi)

print("")
print(cosita)

#inicializaciones
i = 0
error = 100.0

while i < iteraciones and error > tolerancia:

    if i == 0:
        error = 0
        print(f"{i}  {Xo}")
    else:
        if not redondeado:
            print(f"{i}  {X1}            Error: {error}")
        else:
            print(f"{i}  {X1}            Error: " + "{:.10f}".format(error))
        


    X1 = (M @ Xo) + C

    i+=1
    X1Max = np.max(abs(np.abs(X1) - np.abs(Xo)))
    error = X1Max * cosita
    Xo = X1


3.0
0  [0 0 0]
1  [1.625      0.85714286 0.25      ]            Error: 4.8750000000
2  [1.27232143 0.42857143 1.46875   ]            Error: 3.6562500000
3  [1.28069196 0.70344388 1.20424107]            Error: 0.8246173469
4  [1.21067841 0.66326531 1.21051897]            Error: 0.2100406569
5  [1.22496064 0.68416602 1.15800881]            Error: 0.1575304927
6  [1.22368664 0.67258393 1.16872048]            Error: 0.0347462646
7  [1.22669097 0.67447817 1.16776498]            Error: 0.0090129730
8  [1.22610006 0.67348329 1.17001822]            Error: 0.0067597297
9  [1.22619149 0.67397401 1.16957505]            Error: 0.0014721630
10  [1.22606286 0.67388458 1.16964362]            Error: 0.0003858700
11  [1.22608783 0.67393113 1.16954715]            Error: 0.0002894025
12  [1.22608243 0.67391021 1.16956587]            Error: 0.0000627427
13  [1.22608794 0.67391443 1.16956183]            Error: 0.0000165068
14  [1.22608686 0.67391228 1.16956595]            Error: 0.0000123801
15  [1.226087

In [18]:
#Requerimientos
iteraciones = 8
tolerancia = 0.00005
redondeado = False

Xo = np.array([2.5, 5.83333, -2.95238])
X1 = np.array([2.5, 5.83333, -2.95238])

cosita = factor_conM_deSeigel / (1 - factor_conM_deSeigel)

#inicializaciones
i = 0
error = 100.0
j = 0

while i < iteraciones and error > tolerancia:
    
    if i == 0:
        error = 0
        print(f"{i}  {Xo}")
    else:
        if not redondeado:
            print(f"{i}  {X1}            Error: {error}")
        else:
            print(f"{i}  {X1}            Error: " + "{:.10f}".format(error))
    
    while j < cant_filas:
        fila = M[j]
        X1[j] = float(fila @ X1) + C[j]
        j += 1
        
    
    i+=1
    X1Max = np.max(abs(np.abs(X1) - np.abs(Xo)))
    
    #if factor_convergencia <= 0.5:
    #    error = X1Max    
    #else:
    
    error = X1Max * cosita
    
    j = 0
    while j < cant_filas:
        Xo[j] = X1[j]
        j+=1
    j = 0

0  [ 2.5      5.83333 -2.95238]
1  [-0.19345125  0.49064607  0.10491156]            Error: 5.342683928571429
2  [1.42789378 0.46416057 1.32092033]            Error: 1.2344425279017857
3  [1.28582474 0.67846726 1.21436856]            Error: 0.2143066913393426
4  [1.21877871 0.68240159 1.16408403]            Error: 0.06704603729370384
5  [1.2235889  0.67384375 1.16769167]            Error: 0.00855784480715649
6  [1.22634714 0.67357106 1.16976035]            Error: 0.002758236223942223
7  [1.22619081 0.67391125 1.16964311]            Error: 0.0003401898848195417
