
### Comandos Básicos de NumPy

 Creación de Arrays

- ``np.array([lista])``: Crea un array a partir de una lista o lista de listas.
- ``np.zeros((filas, columnas))``: Crea una matriz de ceros.
- ``np.ones((filas, columnas))``: Crea una matriz de unos.
- ``np.eye(N)``: Crea una matriz identidad de tamaño N.
- ``np.arange(inicio, fin, paso)``: Crea un array con valores desde inicio hasta fin con un paso específico.
- ``np.linspace(inicio, fin, num)``: Crea un array de num elementos equidistantes entre inicio y fin.

 Atributos de Arrays

- ``array.shape``: Devuelve una tupla con las dimensiones del array.
- ``array.size``: Devuelve el número total de elementos en el array.
- ``array.ndim``: Devuelve el número de dimensiones del array.
- ``array.dtype``: Devuelve el tipo de dato de los elementos del array.

 Operaciones Básicas

- ``array + array``: Suma de arrays.
- ``array - array``: Resta de arrays.
- ``array * array``: Multiplicación elemento a elemento.
- ``array / array``: División elemento a elemento.
- ``np.dot(array1, array2)``: Producto matricial.
- ``array @ array``: Producto matricial (operador @).

 Funciones Matemáticas

- ``np.sum(array)``: Suma de todos los elementos del array.
- ``np.mean(array)``: Media de los elementos del array.
- ``np.std(array)``: Desviación estándar de los elementos del array.
- ``np.min(array)``: Valor mínimo del array.
- ``np.max(array)``: Valor máximo del array.
- ``np.sqrt(array)``: Raíz cuadrada de cada elemento del array.
- ``np.exp(array)``: Exponencial de cada elemento del array.
- ``np.log(array)``: Logaritmo natural de cada elemento del array.

 Funciones de Indexación y Segmentación

- ``array[index]``: Acceso a un elemento específico.
- ``array[start:stop:step]``: Segmentación de arrays.
- ``np.diagonal(array)``: Devuelve los elementos de la diagonal de una matriz.
- ``np.transpose(array)``: Transpone la matriz.
- ``array.T``: Transpone la matriz (método corto).

 Funciones de Álgebra Lineal

- ``np.linalg.inv(array)``: Inversa de una matriz.
- ``np.linalg.det(array)``: Determinante de una matriz.
- ``np.linalg.eig(array)``: Autovalores y autovectores de una matriz cuadrada.
- ``np.linalg.solve(A, b)``: Resuelve el sistema de ecuaciones lineales Ax = b.

### Decir si una matriz A tiene diagonal Predominante

In [26]:
import numpy as np 

A = np.array([[10, -1,2], [1, -5, 1], [2, -1, 8]])

def tiene_diagonal_predominante(Matriz):
    Mpositiva = np.abs(Matriz)
    cantidad_filas = Mpositiva.shape[0]
    i = 0
    
    while i < cantidad_filas:
        fila = Mpositiva[i]
        diagonal = Mpositiva[i][i]
        if diagonal <= (np.sum(fila) - diagonal):
            return False
        i += 1
    
    
    return True

print(f"La matriz tiene diagonal predominante: {tiene_diagonal_predominante(A)}")

La matriz tiene diagonal predominante: True


### Convertir de una Matriz A y B (Ax = B) a una matriz M y C (X1 = MXo + C)

In [1]:
import numpy as np 

A = np.array([[9.0, -1.0,2.0], [1.0, 8.0, 2.0], [1.0, -1.0, 11.0]])
B = np.array([9.0, 19.0,10.0])

i = 0
n = A.shape[0]

print(f"Matriz A:")
print(f"{A}")
print(f"Matriz B")
print(f"{B}")

print(f"")
print(f"")
print(f"Matriz M:")

while i<n:
    diagonal = A[i][i]
    A[i][i] = 0
    fila = A[i]
    fila = fila / diagonal * -1
    print(fila)
    
    B[i] = B[i] / diagonal
    
    i += 1
    

print(f"Matriz C")
print(f"{B}")



Matriz A:
[[ 9. -1.  2.]
 [ 1.  8.  2.]
 [ 1. -1. 11.]]
Matriz B
[ 9. 19. 10.]


Matriz M:
[-0.          0.11111111 -0.22222222]
[-0.125 -0.    -0.25 ]
[-0.09090909  0.09090909 -0.        ]
Matriz C
[1.         2.375      0.90909091]


### Decir el factor de convergencia tanto con A como con M

In [1]:
import numpy as np

A = np.array([[9.0, -1.0,2.0], [1.0, 8.0, 2.0], [1.0, -1.0, 11.0]])
M = np.array([[0, 1/9,-2/9], [-1/8, 0, -1/4], [-1/11, 1/11, 0]])



def calcular_factor_convergencia_ConA(Matriz):
    Mpositiva = np.abs(Matriz)
    cantidad_filas = Mpositiva.shape[0]
    i = 0
    mayor = -1
    
    while i < cantidad_filas:
        fila = Mpositiva[i]
        diagonal = Mpositiva[i][i]
        
        factorConvergencia = (np.sum(fila) - diagonal) / diagonal
        if factorConvergencia > mayor:
            mayor = factorConvergencia
        i += 1
    
    
    return mayor


def calcular_factor_convergencia_ConM(Matriz):
    Mpositiva = np.abs(Matriz)
    cantidad_filas = Mpositiva.shape[0]
    i = 0
    mayor = -1
    
    while i < cantidad_filas:
        fila = Mpositiva[i]
        factorConvergencia = np.sum(fila) 
        
        if factorConvergencia > mayor:
            mayor = factorConvergencia
        i += 1
    
    
    return mayor

def calcular_factor_convergencia_De_Seigel(Matriz):  #SOlo funciona con M
    Mpositiva = np.abs(Matriz)
    cantidad_filas = Mpositiva.shape[0]
    
    i = 0
    j = 0
    
    Q = 0
    P = 0
    mayor = -1
    esPiso = True
    
    while i < cantidad_filas:  
        while j < cantidad_filas:
            if(j == i):
                esPiso = False
            if(esPiso):
                P += Mpositiva[i][j]
            else:
                Q += Mpositiva[i][j]
            j += 1
        
        factorConvergencia = Q/(1-P)
        
        if factorConvergencia > mayor:
            mayor = factorConvergencia
        
        j = 0
        i += 1
        P = 0
        Q = 0
        esPiso = True
            
         
    return mayor



print(f"El factor de convergencia de JACOBI calculado con A es: {calcular_factor_convergencia_ConA(A)}")
print(f"El factor de convergencia de JACOBI calculado con M es: {calcular_factor_convergencia_ConM(M)}")
print(f"El factor de convergencia de GAUS-SEIGEL calculado con M es: {calcular_factor_convergencia_De_Seigel(M)}")

El factor de convergencia de JACOBI calculado con A es: 0.375
El factor de convergencia de JACOBI calculado con M es: 0.375
El factor de convergencia de GAUS-SEIGEL calculado con M es: 0.3333333333333333


# Metodo Jacobi

In [1]:
import numpy as np

#Datos Que se modifican
M = np.array([[0, 1/9,-2/9], [-1/8, 0, -1/4], [-1/11, 1/11, 0]])
Xo = np.array([0, 0, 0])
c = np.array([9/9, 19/8,10/11])
X1 = np.array([0, 0,0])

factor_convergencia = 0.375  
cosita = factor_convergencia / (1 - factor_convergencia)

#Requerimientos
iteraciones = 8
tolerancia = 0.00005
redondeado = False

#inicializaciones
i = 0
error = 100.0


while i < iteraciones and error > tolerancia:

    if i == 0:
        error = 0
        print(f"{i}  {Xo}")
    else:
        print(f"{i}  {X1}            Error: {error}")


    X1 = (M @ Xo) + c

    i+=1
    X1Max = np.max(abs(np.abs(X1) - np.abs(Xo)))
    error = X1Max * cosita
    Xo = X1
        



0  [0 0 0]
1  [1.         2.375      0.90909091]            Error: 1.425
2  [1.06186869 2.02272727 1.03409091]            Error: 0.2113636363636365
3  [0.99494949 1.98374369 0.99644169]            Error: 0.04015151515151516
4  [0.99898448 2.00152089 0.99898129]            Error: 0.010666322314049648
5  [1.00039537 2.00038162 1.00023058]            Error: 0.0008465335169880684
6  [0.99999116 1.99989293 0.99999875]            Error: 0.00029321060119094075
7  [0.99998838 2.00000142 0.99999107]            Error: 6.509042855280533e-05


# Metodo Gaus-Seigel


In [3]:
import numpy as np

#Datos necesarios
A = np.array([[9.0, -1.0,2.0], [1.0, 8.0, 2.0], [1.0, -1.0, 11.0]])
B = np.array([9.0, 19.0,10.0])

M = np.array([[0, 1/9,-2/9], [-1/8, 0, -1/4], [-1/11, 1/11, 0]])
c = np.array([9/9, 19/8,10/11])
Xo = np.array([0.0, 0.0, 0.0])
X1 = np.array([0.0, 0.0,0.0])


factor_convergencia = 1/3 
cosita = factor_convergencia / (1 - factor_convergencia)


#Requerimientos
iteraciones = 8
tolerancia = 0.00005
redondeado = False


#inicializaciones
i = 0
error = 100.0

#Cosas especiales de este metodo
cantFilas = M.shape[0]
j = 0



while i < iteraciones and error > tolerancia:
    
    if i == 0:
        error = 0
        print(f"{i}  {Xo}")
    else:
        print(f"{i}  {X1}            Error: {error}")
    
    while j < cantFilas:
        fila = M[j]
        X1[j] = float(fila @ X1) + c[j]
        j += 1
        
    
    i+=1
    X1Max = np.max(abs(np.abs(X1) - np.abs(Xo)))
    
    #if factor_convergencia <= 0.5:
    #    error = X1Max    
    #else:
    error = X1Max * cosita
    
    j = 0
    while j < cantFilas:
        Xo[j] = X1[j]
        j+=1
    j = 0

0  [0. 0. 0.]
1  [1.         2.25       1.02272727]            Error: 1.1249999999999998
2  [1.02272727 1.99147727 0.99715909]            Error: 0.12926136363636362
3  [0.99968434 2.00074968 1.00009685]            Error: 0.011521464646464639
4  [1.00006178 1.99996807 0.99999148]            Error: 0.00039080933227464415
